# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Website CI

on:
  push:
    branches: [ main, s3_deploy_test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 17
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Yarn Install
      run: yarn
    - name: Setup config
      run: cp config.prod.js config.js
    - name: Run tests
      run: yarn test
    - name: Build nextjs
      run: yarn next build && yarn next export
    - name: Deploy to s3
      run: aws s3 sync out/. s3://morse.mdp.im/ --exclude 'podcast/*' --exclude 'rss-*.xml' --delete