name: Podcast Production

on:
  schedule:
    - cron:  '41 11,23 * * *'
  workflow_dispatch:

jobs:
  deploy_podcast:
    name: Deploy the podcast
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/base-ffmpeg

    - uses: actions/setup-node@v2
      with:
        node-version: 20
    - run: yarn
    - name: Build 15, 20, and 25 wpm news headlines
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        yarn ts-node podcast/bin/new_podcast.ts -f 10 -w 25 --prefix podcast morse.mdp.im && \
        yarn ts-node podcast/bin/new_podcast.ts -f 15 -w 25 --prefix podcast morse.mdp.im && \
        yarn ts-node podcast/bin/new_podcast.ts -f 20 -w 25 --prefix podcast morse.mdp.im && \
        yarn ts-node podcast/bin/new_podcast.ts -f 25 -w 25 --prefix podcast morse.mdp.im && \
        yarn ts-node podcast/bin/new_podcast.ts -f 30 -w 30 --prefix podcast morse.mdp.im && \
        yarn ts-node podcast/bin/new_podcast.ts -f 35 -w 35 --prefix podcast morse.mdp.im
    - name: Update RSS
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        yarn ts-node podcast/bin/update_rss.ts -f 10 -w 25 --prefix podcast morse.mdp.im && \
        yarn ts-node podcast/bin/update_rss.ts -f 15 -w 25 --prefix podcast morse.mdp.im && \
        yarn ts-node podcast/bin/update_rss.ts -f 20 -w 25 --prefix podcast morse.mdp.im && \
        yarn ts-node podcast/bin/update_rss.ts -f 25 -w 25 --prefix podcast morse.mdp.im && \
        yarn ts-node podcast/bin/update_rss.ts -f 30 -w 30 --prefix podcast morse.mdp.im && \
        yarn ts-node podcast/bin/update_rss.ts -f 35 -w 35 --prefix podcast morse.mdp.im
    - name: Update Headlines for website
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: yarn ts-node podcast/bin/update_headlines.ts --prefix podcast morse.mdp.im
